name: base
dependencies:
  - python=3.10.10
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py310haa95532_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python-utils=3.3.3=py310haa95532_0
  - python_abi=3.10=2_cp310
  - streamlit=1.24.1=pyhd8ed1ab_1
  - pillow=9.4.0=py310hd77b12b_0
  
